pipeline {
    agent any

    tools {
        maven 'Maven 3.9.9'
    }

    options {
        skipStagesAfterUnstable()
    }

    stages {
        stage('Checkout') {
    steps {
        git branch: 'main', url: 'https://github.com/tharunkumarsa/Java_Project.git'
    }
}


        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }

        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }

        stage('Deliver') {
    steps {
        sh 'chmod +x jenkins/scripts/deliver.sh'
        sh './jenkins/scripts/deliver.sh'
    }
}

    }
}
